vhacd: # global vhacd
  use_vhacd: True # whether to use VHACD for collision detection
                    # default: True
                    # True, False
  force_vhacd: False # whether to force creation of VHACD meshes if they are already exists
                     # default: False
                     # False, True
  force_vhacd_urdf: True # whether to force creation of URDF with paths changed to VHACD meshes if it are already exists
                         # default: True
                         # False, True
robot_urdf_path: "../../../UR10e_meshes/ur10e.urdf" # path to Robot URDF file relative to pyur.py
                               # default: "../iCub/full.urdf"
                               # str
gui: False # whether to sho GUI
          # default: True
          # True, False
tolerance:
  joint: 1e-3 # circa 2 degrees
end_effector: "onrobot_rg6_base_link" # end effector name
                       # default: "l_hand"
                       # str
#initial_joint_angles: {"shoulder_lift_joint": -90, "elbow_joint": 90, "shoulder_pan_joint": 90, "wrist_2_joint": 90}
initial_joint_angles: {"shoulder_pan_joint": 4.87, "shoulder_lift_joint": -77.922, "elbow_joint": 98.778, "wrist_1_joint": -17.933, "wrist_2_joint": 94.813, "wrist_3_joint": -3.266}
show_collision: True
urdfs: # other than robot urdfs or .obj files
  paths: [bucket/bucket_1.urdf, bucket/bucket_2.urdf, bucket/bucket_3.urdf, force_measuring_device/fmd.urdf] # path to files relative "other_meshes" directory
  positions: [[0.65, 0.75, 1.45], [-0.3, 0.775, 1.425], [-0.2, -0.1, 1.4], [-0.2, 0.725, 0.0]] # position of the mesh/urdf base link in the world frame
  fixed: [True, True, True, True] # whether the mesh/urdf can move in space
  color: [[], [], [], []] # color on RGB format (0-1)
  force: [0.25, 0.25, 0.25, 15]
#urdfs: # other than robot urdfs or .obj files
#  paths: [] # path to files relative "other_meshes" directory
#  positions: [] # position of the mesh/urdf base link in the world frame
#  fixed: [] # whether the mesh/urdf can move in space
#  color: [] # color on RGB format (0-1)
skin: # skin settings
  use: True # whether to show and simulate skin
              # default: False
              # True, False
  period: 30 # FPS for skin

collision_tolerance: 0.001
debug: False
log: # log settings
  log: False # whether to log data
            # default: True
            # True, False
  period: 0.01 # period of logging
            # default: 0.01
            # float; 0 for logging as fast as every simulation step
            # it will never log faster than the simulation step
simulation_step: 250   # during each simulation step, the simulation time will advance for 1/simulation_step seconds
                       # default: 240 (the default bullet simulation step)
                       # float
                       # the higher, the more precise simulation, but slower simulation
                       # values lower than 200 will most probably break the simulation
self_collisions: True # Whether to detect self collisions of the links of the robot
                       # default: True
                       # True, False
